/// <reference lib="webworker" />
import { precacheAndRoute } from 'workbox-precaching';

declare const self: ServiceWorkerGlobalScope;

// Precache all assets generated by the build
precacheAndRoute(self.__WB_MANIFEST);

interface PushNotificationData {
  title?: string;
  body?: string;
  icon?: string;
  url?: string;
  tag?: string;
}

// Push notification handler
self.addEventListener('push', (event) => {
  console.log('[SW] Push event received:', event);
  
  let data: PushNotificationData = {};
  
  if (event.data) {
    try {
      data = event.data.json();
      console.log('[SW] Push data parsed:', data);
    } catch (e) {
      console.log('[SW] Push data as text:', event.data.text());
      data = { body: event.data.text() };
    }
  }
  
  const options: NotificationOptions = {
    body: data.body || 'Nowa aktywność',
    icon: data.icon || '/pwa-192x192.png',
    badge: '/pwa-192x192.png',
    data: { url: data.url || '/admin' },
    tag: data.tag || 'reservation-' + Date.now(),
    requireInteraction: true,
  };

  console.log('[SW] Showing notification:', data.title, options);

  event.waitUntil(
    self.registration.showNotification(data.title || 'Powiadomienie', options)
  );
});

// Notification click handler - open URL with reservationCode
self.addEventListener('notificationclick', (event) => {
  console.log('[SW] Notification clicked:', event);
  
  event.notification.close();
  
  const url = event.notification.data?.url || '/admin';
  console.log('[SW] Opening URL:', url);
  
  event.waitUntil(
    self.clients.matchAll({ type: 'window', includeUncontrolled: true }).then((windowClients) => {
      // Check if there's already a window open
      for (const client of windowClients) {
        if (client.url.includes('/admin') && 'focus' in client) {
          return client.focus().then(() => {
            if ('navigate' in client) {
              return (client as WindowClient).navigate(url);
            }
          });
        }
      }
      // Open new window if no admin window is open
      return self.clients.openWindow(url);
    })
  );
});

// Service worker install event
self.addEventListener('install', (event) => {
  console.log('[SW] Service Worker installing');
  event.waitUntil(self.skipWaiting());
});

// Service worker activate event
self.addEventListener('activate', (event) => {
  console.log('[SW] Service Worker activating');
  event.waitUntil(self.clients.claim());
});

// Message handler for debugging
self.addEventListener('message', (event) => {
  console.log('[SW] Message received:', event.data);
  
  if (event.data && event.data.type === 'SKIP_WAITING') {
    self.skipWaiting();
  }
});
